import Head from 'next/head'

const Layout = ({ children }) => (
    <>
        <Head>
            <title>Laxmi</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/img/logo.png" />
            <link rel="stylesheet" href="/css/bootstrap.min.css" />
        </Head>
        <main>
            {children}
        </main>
        <footer >

        </footer>
        <script src="/js/bootstrap.bundle.min.js" crossOrigin="anonymous"></script>
    </>    
);

export default Layout;
